package com.psi.thrifter.home

import com.psi.thrifter.R
import com.psi.thrifter.itemData

object dataUtil {

    var itemTrending = listOf(
        itemData(R.drawable.sp1, "Kaos Suprim","Rp 999.999","Toko Alvaro", "Keluaran Terbaik langsung dari konveksi Mempunyai Spesialis Dalam Produksi Pakaian Pria Yang Mana Saat ini Memproduksi Kemeja flanels Berbahan Semi Woll Premium, Dalam industri tekstil dan konveksi, bahan ini sering di sebut kain Flanel yang merupakan salah satu jenis kain dengan bahan dasar Woll Terbaik. inilah jenis bahan yang di sukai oleh orang2 di seluruh dunia, karna tekstur dan permukaannya yang halus, sehingga sanggat lembut dikulit saat digunakan. Cocok Bagi Keseharian Anda yang Ingin Tampil Trendi."),
        itemData(R.drawable.sp2, "Kaos Sungprim","Rp 1.199.999","Toko Adhi", "Keluaran Terbaik langsung dari konveksi Mempunyai Spesialis Dalam Produksi Pakaian Pria Yang Mana Saat ini Memproduksi Kemeja flanels Berbahan Semi Woll Premium, Dalam industri tekstil dan konveksi, bahan ini sering di sebut kain Flanel yang merupakan salah satu jenis kain dengan bahan dasar Woll Terbaik. inilah jenis bahan yang di sukai oleh orang2 di seluruh dunia, karna tekstur dan permukaannya yang halus, sehingga sanggat lembut dikulit saat digunakan. Cocok Bagi Keseharian Anda yang Ingin Tampil Trendi."),
        itemData(R.drawable.sp3, "Kaos Elvi's ORI","Rp 999.899","Toko Evan", "Keluaran Terbaik langsung dari konveksi Mempunyai Spesialis Dalam Produksi Pakaian Pria Yang Mana Saat ini Memproduksi Kemeja flanels Berbahan Semi Woll Premium, Dalam industri tekstil dan konveksi, bahan ini sering di sebut kain Flanel yang merupakan salah satu jenis kain dengan bahan dasar Woll Terbaik. inilah jenis bahan yang di sukai oleh orang2 di seluruh dunia, karna tekstur dan permukaannya yang halus, sehingga sanggat lembut dikulit saat digunakan. Cocok Bagi Keseharian Anda yang Ingin Tampil Trendi."),
        itemData(R.drawable.sp4, "Billabong Special","Rp 2.999.899","Toko Akmal", "Keluaran Terbaik langsung dari konveksi Mempunyai Spesialis Dalam Produksi Pakaian Pria Yang Mana Saat ini Memproduksi Kemeja flanels Berbahan Semi Woll Premium, Dalam industri tekstil dan konveksi, bahan ini sering di sebut kain Flanel yang merupakan salah satu jenis kain dengan bahan dasar Woll Terbaik. inilah jenis bahan yang di sukai oleh orang2 di seluruh dunia, karna tekstur dan permukaannya yang halus, sehingga sanggat lembut dikulit saat digunakan. Cocok Bagi Keseharian Anda yang Ingin Tampil Trendi."),
        itemData(R.drawable.sp5, "Nascar Official","Rp 9.999.999","Toko Banu", "Keluaran Terbaik langsung dari konveksi Mempunyai Spesialis Dalam Produksi Pakaian Pria Yang Mana Saat ini Memproduksi Kemeja flanels Berbahan Semi Woll Premium, Dalam industri tekstil dan konveksi, bahan ini sering di sebut kain Flanel yang merupakan salah satu jenis kain dengan bahan dasar Woll Terbaik. inilah jenis bahan yang di sukai oleh orang2 di seluruh dunia, karna tekstur dan permukaannya yang halus, sehingga sanggat lembut dikulit saat digunakan. Cocok Bagi Keseharian Anda yang Ingin Tampil Trendi.")

    )

    var celanaKategori = listOf(
        itemData(R.drawable.cln1, "Celana Suprim Red","Toko Alvaro", "Rp 999.999","Keluaran Terbaik langsung dari konveksi Mempunyai Spesialis Dalam Produksi Pakaian Pria Yang Mana Saat ini Memproduksi Kemeja flanels Berbahan Semi Woll Premium, Dalam industri tekstil dan konveksi, bahan ini sering di sebut kain Flanel yang merupakan salah satu jenis kain dengan bahan dasar Woll Terbaik. inilah jenis bahan yang di sukai oleh orang2 di seluruh dunia, karna tekstur dan permukaannya yang halus, sehingga sanggat lembut dikulit saat digunakan. Cocok Bagi Keseharian Anda yang Ingin Tampil Trendi."),
        itemData(R.drawable.cln2, "Celana Suprim Black","Toko Adhi", "Rp 1.199.999","Keluaran Terbaik langsung dari konveksi Mempunyai Spesialis Dalam Produksi Pakaian Pria Yang Mana Saat ini Memproduksi Kemeja flanels Berbahan Semi Woll Premium, Dalam industri tekstil dan konveksi, bahan ini sering di sebut kain Flanel yang merupakan salah satu jenis kain dengan bahan dasar Woll Terbaik. inilah jenis bahan yang di sukai oleh orang2 di seluruh dunia, karna tekstur dan permukaannya yang halus, sehingga sanggat lembut dikulit saat digunakan. Cocok Bagi Keseharian Anda yang Ingin Tampil Trendi."),
        itemData(R.drawable.cln3, "Celana Naik Black","Toko Evan", "Rp 999.899","Keluaran Terbaik langsung dari konveksi Mempunyai Spesialis Dalam Produksi Pakaian Pria Yang Mana Saat ini Memproduksi Kemeja flanels Berbahan Semi Woll Premium, Dalam industri tekstil dan konveksi, bahan ini sering di sebut kain Flanel yang merupakan salah satu jenis kain dengan bahan dasar Woll Terbaik. inilah jenis bahan yang di sukai oleh orang2 di seluruh dunia, karna tekstur dan permukaannya yang halus, sehingga sanggat lembut dikulit saat digunakan. Cocok Bagi Keseharian Anda yang Ingin Tampil Trendi."),
        itemData(R.drawable.cln4, "Lepis Panjang","Toko Akmal", "Rp 2.999.899","Keluaran Terbaik langsung dari konveksi Mempunyai Spesialis Dalam Produksi Pakaian Pria Yang Mana Saat ini Memproduksi Kemeja flanels Berbahan Semi Woll Premium, Dalam industri tekstil dan konveksi, bahan ini sering di sebut kain Flanel yang merupakan salah satu jenis kain dengan bahan dasar Woll Terbaik. inilah jenis bahan yang di sukai oleh orang2 di seluruh dunia, karna tekstur dan permukaannya yang halus, sehingga sanggat lembut dikulit saat digunakan. Cocok Bagi Keseharian Anda yang Ingin Tampil Trendi."),
        itemData(R.drawable.cln5, "Celana Bahan","Toko Banu", "Rp 9.999.999","Keluaran Terbaik langsung dari konveksi Mempunyai Spesialis Dalam Produksi Pakaian Pria Yang Mana Saat ini Memproduksi Kemeja flanels Berbahan Semi Woll Premium, Dalam industri tekstil dan konveksi, bahan ini sering di sebut kain Flanel yang merupakan salah satu jenis kain dengan bahan dasar Woll Terbaik. inilah jenis bahan yang di sukai oleh orang2 di seluruh dunia, karna tekstur dan permukaannya yang halus, sehingga sanggat lembut dikulit saat digunakan. Cocok Bagi Keseharian Anda yang Ingin Tampil Trendi.")
    )

    var topiKategori = listOf(
        itemData(R.drawable.tp1, "Topi Keren ","Toko Alvaro", "Rp 999.999","Keluaran Terbaik langsung dari konveksi Mempunyai Spesialis Dalam Produksi Pakaian Pria Yang Mana Saat ini Memproduksi Kemeja flanels Berbahan Semi Woll Premium, Dalam industri tekstil dan konveksi, bahan ini sering di sebut kain Flanel yang merupakan salah satu jenis kain dengan bahan dasar Woll Terbaik. inilah jenis bahan yang di sukai oleh orang2 di seluruh dunia, karna tekstur dan permukaannya yang halus, sehingga sanggat lembut dikulit saat digunakan. Cocok Bagi Keseharian Anda yang Ingin Tampil Trendi."),
        itemData(R.drawable.tp2, "Topi GG Gimank","Toko Adhi", "Rp 1.199.999","Keluaran Terbaik langsung dari konveksi Mempunyai Spesialis Dalam Produksi Pakaian Pria Yang Mana Saat ini Memproduksi Kemeja flanels Berbahan Semi Woll Premium, Dalam industri tekstil dan konveksi, bahan ini sering di sebut kain Flanel yang merupakan salah satu jenis kain dengan bahan dasar Woll Terbaik. inilah jenis bahan yang di sukai oleh orang2 di seluruh dunia, karna tekstur dan permukaannya yang halus, sehingga sanggat lembut dikulit saat digunakan. Cocok Bagi Keseharian Anda yang Ingin Tampil Trendi."),
        itemData(R.drawable.tp3, "Topi si No 1","Toko Evan", "Rp 999.899","Keluaran Terbaik langsung dari konveksi Mempunyai Spesialis Dalam Produksi Pakaian Pria Yang Mana Saat ini Memproduksi Kemeja flanels Berbahan Semi Woll Premium, Dalam industri tekstil dan konveksi, bahan ini sering di sebut kain Flanel yang merupakan salah satu jenis kain dengan bahan dasar Woll Terbaik. inilah jenis bahan yang di sukai oleh orang2 di seluruh dunia, karna tekstur dan permukaannya yang halus, sehingga sanggat lembut dikulit saat digunakan. Cocok Bagi Keseharian Anda yang Ingin Tampil Trendi."),
        itemData(R.drawable.tp4, "Topi Ngabers","Toko Akmal", "Rp 2.999.899","Keluaran Terbaik langsung dari konveksi Mempunyai Spesialis Dalam Produksi Pakaian Pria Yang Mana Saat ini Memproduksi Kemeja flanels Berbahan Semi Woll Premium, Dalam industri tekstil dan konveksi, bahan ini sering di sebut kain Flanel yang merupakan salah satu jenis kain dengan bahan dasar Woll Terbaik. inilah jenis bahan yang di sukai oleh orang2 di seluruh dunia, karna tekstur dan permukaannya yang halus, sehingga sanggat lembut dikulit saat digunakan. Cocok Bagi Keseharian Anda yang Ingin Tampil Trendi."),
        itemData(R.drawable.tp5, "Topi ketampanan","Toko Banu", "Rp 9.999.999","Keluaran Terbaik langsung dari konveksi Mempunyai Spesialis Dalam Produksi Pakaian Pria Yang Mana Saat ini Memproduksi Kemeja flanels Berbahan Semi Woll Premium, Dalam industri tekstil dan konveksi, bahan ini sering di sebut kain Flanel yang merupakan salah satu jenis kain dengan bahan dasar Woll Terbaik. inilah jenis bahan yang di sukai oleh orang2 di seluruh dunia, karna tekstur dan permukaannya yang halus, sehingga sanggat lembut dikulit saat digunakan. Cocok Bagi Keseharian Anda yang Ingin Tampil Trendi.")
    )

    var sepatuKategori = listOf(
        itemData(R.drawable.spt1, "Sepatu Naik Red ","Toko Alvaro", "Rp 999.999","Keluaran Terbaik langsung dari konveksi Mempunyai Spesialis Dalam Produksi Pakaian Pria Yang Mana Saat ini Memproduksi Kemeja flanels Berbahan Semi Woll Premium, Dalam industri tekstil dan konveksi, bahan ini sering di sebut kain Flanel yang merupakan salah satu jenis kain dengan bahan dasar Woll Terbaik. inilah jenis bahan yang di sukai oleh orang2 di seluruh dunia, karna tekstur dan permukaannya yang halus, sehingga sanggat lembut dikulit saat digunakan. Cocok Bagi Keseharian Anda yang Ingin Tampil Trendi."),
        itemData(R.drawable.spt2, "Sepatu ImBalance Blue","Toko Adhi", "Rp 1.199.999","Keluaran Terbaik langsung dari konveksi Mempunyai Spesialis Dalam Produksi Pakaian Pria Yang Mana Saat ini Memproduksi Kemeja flanels Berbahan Semi Woll Premium, Dalam industri tekstil dan konveksi, bahan ini sering di sebut kain Flanel yang merupakan salah satu jenis kain dengan bahan dasar Woll Terbaik. inilah jenis bahan yang di sukai oleh orang2 di seluruh dunia, karna tekstur dan permukaannya yang halus, sehingga sanggat lembut dikulit saat digunakan. Cocok Bagi Keseharian Anda yang Ingin Tampil Trendi."),
        itemData(R.drawable.spt3, "Sepatu Bagogo Tosca","Toko Evan", "Rp 999.899","Keluaran Terbaik langsung dari konveksi Mempunyai Spesialis Dalam Produksi Pakaian Pria Yang Mana Saat ini Memproduksi Kemeja flanels Berbahan Semi Woll Premium, Dalam industri tekstil dan konveksi, bahan ini sering di sebut kain Flanel yang merupakan salah satu jenis kain dengan bahan dasar Woll Terbaik. inilah jenis bahan yang di sukai oleh orang2 di seluruh dunia, karna tekstur dan permukaannya yang halus, sehingga sanggat lembut dikulit saat digunakan. Cocok Bagi Keseharian Anda yang Ingin Tampil Trendi."),
        itemData(R.drawable.spt4, "Sepatu Adudu Navy","Toko Akmal", "Rp 2.999.899","Keluaran Terbaik langsung dari konveksi Mempunyai Spesialis Dalam Produksi Pakaian Pria Yang Mana Saat ini Memproduksi Kemeja flanels Berbahan Semi Woll Premium, Dalam industri tekstil dan konveksi, bahan ini sering di sebut kain Flanel yang merupakan salah satu jenis kain dengan bahan dasar Woll Terbaik. inilah jenis bahan yang di sukai oleh orang2 di seluruh dunia, karna tekstur dan permukaannya yang halus, sehingga sanggat lembut dikulit saat digunakan. Cocok Bagi Keseharian Anda yang Ingin Tampil Trendi."),
        itemData(R.drawable.spt5, "Sepatu Adida White","Toko Banu", "Rp 9.999.999","Keluaran Terbaik langsung dari konveksi Mempunyai Spesialis Dalam Produksi Pakaian Pria Yang Mana Saat ini Memproduksi Kemeja flanels Berbahan Semi Woll Premium, Dalam industri tekstil dan konveksi, bahan ini sering di sebut kain Flanel yang merupakan salah satu jenis kain dengan bahan dasar Woll Terbaik. inilah jenis bahan yang di sukai oleh orang2 di seluruh dunia, karna tekstur dan permukaannya yang halus, sehingga sanggat lembut dikulit saat digunakan. Cocok Bagi Keseharian Anda yang Ingin Tampil Trendi.")
    )


}

